name: GitHub Actions Linter

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
