[tool.bumpversion]
current_version = "1.4.2"
commit = false
tag = false

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "uv.lock"
search = 'name = "slack-notifier"\nversion = "{current_version}"'
replace = 'name = "slack-notifier"\nversion = "{new_version}"'
regex = true
