[project]
name = "slack-notifier"
version = "1.0.1"
description = "A simple Python module for sending Slack notifications"
authors = [
    { name = "Riki Nakamura", email = "riki.nakamura.edu@gmail.com" }
]
dependencies = [
    "slack-sdk>=3.32.0",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ruff>=0.6.4",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/slack_notifier"]

[tool.ruff]
target-version = "py312"
line-length = 120
