[project]
name = "slack-notifier"
version = "1.1.3"
description = "A simple Python package for sending Slack notifications"
authors = [
    { name = "Riki Nakamura", email = "riki.nakamura.edu@gmail.com" }
]
dependencies = [
    "rich>=13.9.4",
    "slack-sdk>=3.32.0",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
managed = true
dev-dependencies = [
    "bump-my-version==0.28.3",
    "ruff==0.8.1",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/slack_notifier"]

[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D211", "D213"]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["INP001", "S105"]
