name: "Bump Version"

on:
  pull_request:
    types: [closed]

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: conjikidow/bump-version@5a63a3a3c8c817304389f557bdd382ea95ef4138 # v1.2.2
        with:
          label-major: "update::major"
          label-minor: "update::minor"
          label-patch: "update::patch"
          labels-to-add: "automated,versioning"
