name: Lint Python

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/lint_python.yaml'
      - 'pyproject.toml'
      - '.python-version'
      - 'src/**.py'
      - 'tests/**.py'
      - 'uv.lock'

jobs:

  ruff:
    name: ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5.2.0

      - name: Set up Python environment using uv
        run: |
          uv sync

      - name: Check tools version
        run: |
          uv --version
          uv run ruff --version

      - name: Lint with Ruff
        run: |
          uv run ruff check . --output-format=github
