name: Python Linter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python environment using uv
        run: |
          uv sync

      - name: Check tools version
        run: |
          uv --version
          uv run ruff --version

      - name: Lint with Ruff
        run: |
          uv run ruff check . --output-format=github
