name: Run Pytest

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/run_pytest.yaml'
      - 'pyproject.toml'
      - '.python-version'
      - 'src/**.py'
      - 'tests/**.py'
      - 'uv.lock'

jobs:

  pytest:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5.2.2

      - name: Set up Python environment using uv
        run: |
          uv sync

      - name: Check tools version
        run: |
          uv --version
          uv run pytest --version

      - name: Test with Pytest
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          uv run pytest
